apiVersion: v1
kind: Namespace
metadata:
  name: user1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: user1:admins
 namespace: user1
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user1-admins
  namespace: user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user1:admins
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: user1:admins